name: Build and Release Python Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Create Executable using PyInstaller
      run: |
        pyinstaller --onefile --name XIKILAND --icon icons/xikiland_icon.ico --noconsole main.py

    - name: Create Git tag
      id: create_tag
      run: |
        $VERSION_FILE = "version.txt"
        $VERSION_PREFIX = Get-Content $VERSION_FILE
        git fetch --tags
        $LATEST_TAG = git tag --list "$VERSION_PREFIX*" | Sort-Object -Descending | Select-Object -First 1
    
        if (-not $LATEST_TAG) {
          $NEW_TAG = "$VERSION_PREFIX" + "0"
        } else {
          $TAG_PARTS = $LATEST_TAG -split '\.'
          $TAG_PARTS[-1] = [int]$TAG_PARTS[-1] + 1
          $NEW_TAG = ($TAG_PARTS -join '.')
        }
    
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git tag $NEW_TAG
        git push origin $NEW_TAG
        echo "tag=$NEW_TAG" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

    - name: Upload executable to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/XIKILAND.exe
        tag_name: ${{ env.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
