name: Build and Release Python Executable

on:
  push:
    branches:
      - main
  # Puedes descomentar esto si deseas ejecutar el flujo de trabajo en pull requests
  # pull_request:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Download icon
      run: |
        mkdir -p icons
        curl -L -o icons/xikiland_icon.ico https://raw.githubusercontent.com/dvo18/xikiland_exe/main/icons/xikiland_icon.ico

    - name: Create Executable using PyInstaller
      run: |
        pyinstaller --onefile --windowed --name client_XIKILAND2 --icon icons/xikiland_icon.ico main.py

    - name: Create Git tag
      id: create_tag
      run: |
        VERSION_FILE="version.txt"
        if [ -f "$VERSION_FILE" ]; then
          CURRENT_VERSION=$(cat $VERSION_FILE)
          NEW_VERSION=$(echo "$CURRENT_VERSION" | awk -F. -v OFS=. '{$NF++;print}')
        else
          NEW_VERSION="v1.0.0"
        fi
        echo $NEW_VERSION > $VERSION_FILE
        git tag $NEW_VERSION
        git push origin $NEW_VERSION
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload executable to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: dist/client_XIKILAND2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
